services:
  discord_bot:
    image: osrs-discord-bot:latest
    build:
      context: .
      target: prod
      args:
        MIX_ENV: prod
        ELIXIR_VERSION: 1.18.4
    restart: unless-stopped
    volumes:
      - '/opt/discord_bot:/opt/app/data'
